services:
  - type: web
    name: mei-drive-backend
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: BACKEND_URL
        value: https://meidriveafrica-backend.onrender.com
      - key: MPESA_CONSUMER_KEY
        value: LI2gcJZEheN8qCfXHEXV4gdYXvOBHVnv
      - key: MPESA_CONSUMER_SECRET
        value: aGGo8AuPJVpsZLcs
      - key: MPESA_PASSKEY
        value: 7eb17a031bdfd5b4251863a1ddb72c5b9cd14f3385aa6a258c1442a0116e8277
      - key: MPESA_SHORTCODE
        value: 4095377
      - key: MPESA_CALLBACK_URL
        value: https://meidriveafrica-backend.onrender.com/api/payments/mpesa/callback
